// withReactJs/src/App.jsx
// App.js
import React, { useEffect, useState } from "react";
import TodoForm from "./components/TodoForm";
import TodoList from "./components/TodoList";

function App() {
  const [todos, setTodos] = useState([]);

  //for getting todos from local storage
  useEffect(() => {
    const storedTodos = JSON.parse(localStorage.getItem("formEntries")) || [];
    setTodos(storedTodos);
  }, []);


  const addTodo = (newTodo) => {
    const newEntry = { ...newTodo, id: Date.now() };
    const updatedTodos = [...todos, newEntry];
    setTodos(updatedTodos);
    localStorage.setItem("formEntries", JSON.stringify(updatedTodos));
  };
  const deleteTodo = (id) => {
    
    setTodos(todos.filter((todo) => todo.id !== id));

  }
  return (
    <div className="app-container">
      <h1 className="app-title text-brown">Welcome to my Todo List</h1>
      <div className="todo-app">
        <TodoForm addTodo={addTodo} />
        <TodoList todos={todos} setTodos={setTodos} deleteTodo={deleteTodo}/>
      </div>
    </div>
  );
}

export default App;

// todowithselv/todo-app/src/App.svelte
<script>
  // import { onMount } from 'svelte';
  import BG from './lib/BG.svelte';
  import TodoInput from './lib/TodoInput.svelte';
  import TodoList from './lib/TodoList.svelte';

  let newTodo = '';
  let todos = [];

//   onMount(() => {
//   const stored = localStorage.getItem('todos');
//   if (stored) {
//     todos = JSON.parse(stored);
//   }
// });

  function addTodo() {
    if (newTodo.trim()) {
      todos = [...todos, { text: newTodo, completed: false }];
      newTodo = '';
    }
  }

  function toggleTodo(index) {
    todos[index].completed = !todos[index].completed;
    todos = [...todos];
  }

  function deleteTodo(index) {
    todos = todos.filter((_, i) => i !== index);
  }
</script>
 <BG />
<main class="app">
 
  <h1 class="title">📝 My To-Do List</h1>

  <TodoInput
    {newTodo}
    onInput={(e) => newTodo = e.target.value}
    onAdd={addTodo}
  />

  <TodoList
    {todos}
    {toggleTodo}
    {deleteTodo}
  />
</main>
